#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CustomPresenter.Android.Resource", IsApplication=true)]

namespace CustomPresenter.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Intersoft.Crosslight.Android.Resource.Animation.slide_in_top = global::CustomPresenter.Android.Resource.Animation.slide_in_top;
			global::Intersoft.Crosslight.Android.Resource.Animation.slide_out_top = global::CustomPresenter.Android.Resource.Animation.slide_out_top;
			global::Intersoft.Crosslight.Android.Resource.Animation.toast_enter = global::CustomPresenter.Android.Resource.Animation.toast_enter;
			global::Intersoft.Crosslight.Android.Resource.Animation.toast_exit = global::CustomPresenter.Android.Resource.Animation.toast_exit;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_bottomtop = global::CustomPresenter.Android.Resource.Animation.transition_bottomtop;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_fadein = global::CustomPresenter.Android.Resource.Animation.transition_fadein;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_fadeout = global::CustomPresenter.Android.Resource.Animation.transition_fadeout;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_leftright = global::CustomPresenter.Android.Resource.Animation.transition_leftright;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_rightleft = global::CustomPresenter.Android.Resource.Animation.transition_rightleft;
			global::Intersoft.Crosslight.Android.Resource.Animation.transition_topbottom = global::CustomPresenter.Android.Resource.Animation.transition_topbottom;
			global::Intersoft.Crosslight.Android.Resource.Array.select_image_dialog = global::CustomPresenter.Android.Resource.Array.select_image_dialog;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrHeaderBackground = global::CustomPresenter.Android.Resource.Attribute.ptrHeaderBackground;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrHeaderHeight = global::CustomPresenter.Android.Resource.Attribute.ptrHeaderHeight;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrHeaderStyle = global::CustomPresenter.Android.Resource.Attribute.ptrHeaderStyle;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrHeaderTitleTextAppearance = global::CustomPresenter.Android.Resource.Attribute.ptrHeaderTitleTextAppearance;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrProgressBarColor = global::CustomPresenter.Android.Resource.Attribute.ptrProgressBarColor;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrProgressBarHeight = global::CustomPresenter.Android.Resource.Attribute.ptrProgressBarHeight;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrProgressBarStyle = global::CustomPresenter.Android.Resource.Attribute.ptrProgressBarStyle;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrPullText = global::CustomPresenter.Android.Resource.Attribute.ptrPullText;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrRefreshingText = global::CustomPresenter.Android.Resource.Attribute.ptrRefreshingText;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrReleaseText = global::CustomPresenter.Android.Resource.Attribute.ptrReleaseText;
			global::Intersoft.Crosslight.Android.Resource.Attribute.ptrViewDelegateClass = global::CustomPresenter.Android.Resource.Attribute.ptrViewDelegateClass;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spbStyle = global::CustomPresenter.Android.Resource.Attribute.spbStyle;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_color = global::CustomPresenter.Android.Resource.Attribute.spb_color;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_colors = global::CustomPresenter.Android.Resource.Attribute.spb_colors;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_interpolator = global::CustomPresenter.Android.Resource.Attribute.spb_interpolator;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_mirror_mode = global::CustomPresenter.Android.Resource.Attribute.spb_mirror_mode;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_reversed = global::CustomPresenter.Android.Resource.Attribute.spb_reversed;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_sections_count = global::CustomPresenter.Android.Resource.Attribute.spb_sections_count;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_speed = global::CustomPresenter.Android.Resource.Attribute.spb_speed;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_stroke_separator_length = global::CustomPresenter.Android.Resource.Attribute.spb_stroke_separator_length;
			global::Intersoft.Crosslight.Android.Resource.Attribute.spb_stroke_width = global::CustomPresenter.Android.Resource.Attribute.spb_stroke_width;
			global::Intersoft.Crosslight.Android.Resource.Boolean.spb_default_mirror_mode = global::CustomPresenter.Android.Resource.Boolean.spb_default_mirror_mode;
			global::Intersoft.Crosslight.Android.Resource.Boolean.spb_default_reversed = global::CustomPresenter.Android.Resource.Boolean.spb_default_reversed;
			global::Intersoft.Crosslight.Android.Resource.Color.bright_foreground_dark = global::CustomPresenter.Android.Resource.Color.bright_foreground_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.default_progress_bar_color = global::CustomPresenter.Android.Resource.Color.default_progress_bar_color;
			global::Intersoft.Crosslight.Android.Resource.Color.holo_dark_green = global::CustomPresenter.Android.Resource.Color.holo_dark_green;
			global::Intersoft.Crosslight.Android.Resource.Color.listviewbackgroundselector = global::CustomPresenter.Android.Resource.Color.listviewbackgroundselector;
			global::Intersoft.Crosslight.Android.Resource.Color.spb_default_color = global::CustomPresenter.Android.Resource.Color.spb_default_color;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__background_holo_dark = global::CustomPresenter.Android.Resource.Color.vpi__background_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__background_holo_light = global::CustomPresenter.Android.Resource.Color.vpi__background_holo_light;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_holo_dark = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_holo_light = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_holo_light;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::CustomPresenter.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::Intersoft.Crosslight.Android.Resource.Color.vpi__dark_theme = global::CustomPresenter.Android.Resource.Color.vpi__dark_theme;
			global::Intersoft.Crosslight.Android.Resource.Dimension.ptr_progress_bar_stroke_width = global::CustomPresenter.Android.Resource.Dimension.ptr_progress_bar_stroke_width;
			global::Intersoft.Crosslight.Android.Resource.Dimension.spb_default_stroke_separator_length = global::CustomPresenter.Android.Resource.Dimension.spb_default_stroke_separator_length;
			global::Intersoft.Crosslight.Android.Resource.Dimension.spb_default_stroke_width = global::CustomPresenter.Android.Resource.Dimension.spb_default_stroke_width;
			global::Intersoft.Crosslight.Android.Resource.Drawable.btn_check_off_focused_holo_dark = global::CustomPresenter.Android.Resource.Drawable.btn_check_off_focused_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Drawable.btn_check_on_pressed_holo_dark = global::CustomPresenter.Android.Resource.Drawable.btn_check_on_pressed_holo_dark;
			global::Intersoft.Crosslight.Android.Resource.Drawable.ic_drawer = global::CustomPresenter.Android.Resource.Drawable.ic_drawer;
			global::Intersoft.Crosslight.Android.Resource.Drawable.leftdrawershadow = global::CustomPresenter.Android.Resource.Drawable.leftdrawershadow;
			global::Intersoft.Crosslight.Android.Resource.Drawable.rightdrawershadow = global::CustomPresenter.Android.Resource.Drawable.rightdrawershadow;
			global::Intersoft.Crosslight.Android.Resource.Drawable.toast_frame_holo = global::CustomPresenter.Android.Resource.Drawable.toast_frame_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_indicator = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_indicator;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_selected_focused_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_selected_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_selected_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_selected_pressed_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_unselected_focused_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_unselected_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_unselected_holo;
			global::Intersoft.Crosslight.Android.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::CustomPresenter.Android.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::Intersoft.Crosslight.Android.Resource.Id.ControlsPlaceholder = global::CustomPresenter.Android.Resource.Id.ControlsPlaceholder;
			global::Intersoft.Crosslight.Android.Resource.Id.DatePickerWidget = global::CustomPresenter.Android.Resource.Id.DatePickerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.DateTimePickerDateWidget = global::CustomPresenter.Android.Resource.Id.DateTimePickerDateWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.DateTimePickerTimeWidget = global::CustomPresenter.Android.Resource.Id.DateTimePickerTimeWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.EditorContainer = global::CustomPresenter.Android.Resource.Id.EditorContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.FooterLayout = global::CustomPresenter.Android.Resource.Id.FooterLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.FooterText = global::CustomPresenter.Android.Resource.Id.FooterText;
			global::Intersoft.Crosslight.Android.Resource.Id.FormContainer = global::CustomPresenter.Android.Resource.Id.FormContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderLayout = global::CustomPresenter.Android.Resource.Id.HeaderLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderSeparator = global::CustomPresenter.Android.Resource.Id.HeaderSeparator;
			global::Intersoft.Crosslight.Android.Resource.Id.HeaderText = global::CustomPresenter.Android.Resource.Id.HeaderText;
			global::Intersoft.Crosslight.Android.Resource.Id.ImagePlaceholder = global::CustomPresenter.Android.Resource.Id.ImagePlaceholder;
			global::Intersoft.Crosslight.Android.Resource.Id.ImageView = global::CustomPresenter.Android.Resource.Id.ImageView;
			global::Intersoft.Crosslight.Android.Resource.Id.InnerLayout = global::CustomPresenter.Android.Resource.Id.InnerLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.InternalSeekBar = global::CustomPresenter.Android.Resource.Id.InternalSeekBar;
			global::Intersoft.Crosslight.Android.Resource.Id.PagerTabStrip = global::CustomPresenter.Android.Resource.Id.PagerTabStrip;
			global::Intersoft.Crosslight.Android.Resource.Id.SpinnerWidget = global::CustomPresenter.Android.Resource.Id.SpinnerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.Switch = global::CustomPresenter.Android.Resource.Id.Switch;
			global::Intersoft.Crosslight.Android.Resource.Id.TabContainer = global::CustomPresenter.Android.Resource.Id.TabContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.TabIcon = global::CustomPresenter.Android.Resource.Id.TabIcon;
			global::Intersoft.Crosslight.Android.Resource.Id.TabPageIndicator = global::CustomPresenter.Android.Resource.Id.TabPageIndicator;
			global::Intersoft.Crosslight.Android.Resource.Id.TabTitle = global::CustomPresenter.Android.Resource.Id.TabTitle;
			global::Intersoft.Crosslight.Android.Resource.Id.Text1 = global::CustomPresenter.Android.Resource.Id.Text1;
			global::Intersoft.Crosslight.Android.Resource.Id.Text2 = global::CustomPresenter.Android.Resource.Id.Text2;
			global::Intersoft.Crosslight.Android.Resource.Id.TimePickerWidget = global::CustomPresenter.Android.Resource.Id.TimePickerWidget;
			global::Intersoft.Crosslight.Android.Resource.Id.TitleText = global::CustomPresenter.Android.Resource.Id.TitleText;
			global::Intersoft.Crosslight.Android.Resource.Id.ViewPager = global::CustomPresenter.Android.Resource.Id.ViewPager;
			global::Intersoft.Crosslight.Android.Resource.Id.detailFrame = global::CustomPresenter.Android.Resource.Id.detailFrame;
			global::Intersoft.Crosslight.Android.Resource.Id.drawer_layout = global::CustomPresenter.Android.Resource.Id.drawer_layout;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentActivityLayout = global::CustomPresenter.Android.Resource.Id.fragmentActivityLayout;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentBody = global::CustomPresenter.Android.Resource.Id.fragmentBody;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentFooter = global::CustomPresenter.Android.Resource.Id.fragmentFooter;
			global::Intersoft.Crosslight.Android.Resource.Id.fragmentHeader = global::CustomPresenter.Android.Resource.Id.fragmentHeader;
			global::Intersoft.Crosslight.Android.Resource.Id.inside = global::CustomPresenter.Android.Resource.Id.inside;
			global::Intersoft.Crosslight.Android.Resource.Id.left_navdrawer = global::CustomPresenter.Android.Resource.Id.left_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Id.listContainer = global::CustomPresenter.Android.Resource.Id.listContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.listViewFooter = global::CustomPresenter.Android.Resource.Id.listViewFooter;
			global::Intersoft.Crosslight.Android.Resource.Id.listViewHeader = global::CustomPresenter.Android.Resource.Id.listViewHeader;
			global::Intersoft.Crosslight.Android.Resource.Id.listViewProgressbar = global::CustomPresenter.Android.Resource.Id.listViewProgressbar;
			global::Intersoft.Crosslight.Android.Resource.Id.maincontent_navdrawer = global::CustomPresenter.Android.Resource.Id.maincontent_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Id.masterFrame = global::CustomPresenter.Android.Resource.Id.masterFrame;
			global::Intersoft.Crosslight.Android.Resource.Id.outside = global::CustomPresenter.Android.Resource.Id.outside;
			global::Intersoft.Crosslight.Android.Resource.Id.progressContainer = global::CustomPresenter.Android.Resource.Id.progressContainer;
			global::Intersoft.Crosslight.Android.Resource.Id.progress_bar = global::CustomPresenter.Android.Resource.Id.progress_bar;
			global::Intersoft.Crosslight.Android.Resource.Id.ptr_content = global::CustomPresenter.Android.Resource.Id.ptr_content;
			global::Intersoft.Crosslight.Android.Resource.Id.ptr_progress = global::CustomPresenter.Android.Resource.Id.ptr_progress;
			global::Intersoft.Crosslight.Android.Resource.Id.ptr_text = global::CustomPresenter.Android.Resource.Id.ptr_text;
			global::Intersoft.Crosslight.Android.Resource.Id.right_navdrawer = global::CustomPresenter.Android.Resource.Id.right_navdrawer;
			global::Intersoft.Crosslight.Android.Resource.Id.spb_interpolator_accelerate = global::CustomPresenter.Android.Resource.Id.spb_interpolator_accelerate;
			global::Intersoft.Crosslight.Android.Resource.Id.spb_interpolator_acceleratedecelerate = global::CustomPresenter.Android.Resource.Id.spb_interpolator_acceleratedecelerate;
			global::Intersoft.Crosslight.Android.Resource.Id.spb_interpolator_decelerate = global::CustomPresenter.Android.Resource.Id.spb_interpolator_decelerate;
			global::Intersoft.Crosslight.Android.Resource.Id.spb_interpolator_linear = global::CustomPresenter.Android.Resource.Id.spb_interpolator_linear;
			global::Intersoft.Crosslight.Android.Resource.Integer.spb_default_interpolator = global::CustomPresenter.Android.Resource.Integer.spb_default_interpolator;
			global::Intersoft.Crosslight.Android.Resource.Integer.spb_default_sections_count = global::CustomPresenter.Android.Resource.Integer.spb_default_sections_count;
			global::Intersoft.Crosslight.Android.Resource.Interpolator.accelerate_quad = global::CustomPresenter.Android.Resource.Interpolator.accelerate_quad;
			global::Intersoft.Crosslight.Android.Resource.Interpolator.decelerate_quad = global::CustomPresenter.Android.Resource.Interpolator.decelerate_quad;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitylargeindicator = global::CustomPresenter.Android.Resource.Layout.activitylargeindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitysmallindicator = global::CustomPresenter.Android.Resource.Layout.activitysmallindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.activitytranslucentindicator = global::CustomPresenter.Android.Resource.Layout.activitytranslucentindicator;
			global::Intersoft.Crosslight.Android.Resource.Layout.buttonwidget = global::CustomPresenter.Android.Resource.Layout.buttonwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.checkboxwidget = global::CustomPresenter.Android.Resource.Layout.checkboxwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.datepickerwidget = global::CustomPresenter.Android.Resource.Layout.datepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.datetimepickerwidget = global::CustomPresenter.Android.Resource.Layout.datetimepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.default_header = global::CustomPresenter.Android.Resource.Layout.default_header;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayout = global::CustomPresenter.Android.Resource.Layout.formlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutdetailonly = global::CustomPresenter.Android.Resource.Layout.formlayoutdetailonly;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutleftdetail = global::CustomPresenter.Android.Resource.Layout.formlayoutleftdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutrightdetail = global::CustomPresenter.Android.Resource.Layout.formlayoutrightdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formlayoutrowdetail = global::CustomPresenter.Android.Resource.Layout.formlayoutrowdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.formsectionlayout = global::CustomPresenter.Android.Resource.Layout.formsectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.fragmentactivitylayout = global::CustomPresenter.Android.Resource.Layout.fragmentactivitylayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.imagepickerwidget = global::CustomPresenter.Android.Resource.Layout.imagepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.imageviewwidget = global::CustomPresenter.Android.Resource.Layout.imageviewwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.listgroupsectionheaderlayout = global::CustomPresenter.Android.Resource.Layout.listgroupsectionheaderlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listgroupsectionlayout = global::CustomPresenter.Android.Resource.Layout.listgroupsectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listviewfooterlayout = global::CustomPresenter.Android.Resource.Layout.listviewfooterlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listviewheaderlayout = global::CustomPresenter.Android.Resource.Layout.listviewheaderlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.listviewprogressbarlayout = global::CustomPresenter.Android.Resource.Layout.listviewprogressbarlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.maincontainer = global::CustomPresenter.Android.Resource.Layout.maincontainer;
			global::Intersoft.Crosslight.Android.Resource.Layout.masterdetailfragmentlayout = global::CustomPresenter.Android.Resource.Layout.masterdetailfragmentlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.navigationdrawerlayout = global::CustomPresenter.Android.Resource.Layout.navigationdrawerlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.radiobuttonwidget = global::CustomPresenter.Android.Resource.Layout.radiobuttonwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.sectionimageswithfieldslayout = global::CustomPresenter.Android.Resource.Layout.sectionimageswithfieldslayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.sectionlayout = global::CustomPresenter.Android.Resource.Layout.sectionlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.seekbarwidget = global::CustomPresenter.Android.Resource.Layout.seekbarwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.selectionwidget = global::CustomPresenter.Android.Resource.Layout.selectionwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerdropdownitemlayout = global::CustomPresenter.Android.Resource.Layout.spinnerdropdownitemlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerlayout = global::CustomPresenter.Android.Resource.Layout.spinnerlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.spinnerwidget = global::CustomPresenter.Android.Resource.Layout.spinnerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.switchwidget = global::CustomPresenter.Android.Resource.Layout.switchwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.tabcontainer = global::CustomPresenter.Android.Resource.Layout.tabcontainer;
			global::Intersoft.Crosslight.Android.Resource.Layout.tabfragmentlayout = global::CustomPresenter.Android.Resource.Layout.tabfragmentlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellleftdetail = global::CustomPresenter.Android.Resource.Layout.tablecellleftdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellrightdetail = global::CustomPresenter.Android.Resource.Layout.tablecellrightdetail;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellsubtitle = global::CustomPresenter.Android.Resource.Layout.tablecellsubtitle;
			global::Intersoft.Crosslight.Android.Resource.Layout.tablecellsubtitlewithimage = global::CustomPresenter.Android.Resource.Layout.tablecellsubtitlewithimage;
			global::Intersoft.Crosslight.Android.Resource.Layout.textfieldview = global::CustomPresenter.Android.Resource.Layout.textfieldview;
			global::Intersoft.Crosslight.Android.Resource.Layout.timepickerwidget = global::CustomPresenter.Android.Resource.Layout.timepickerwidget;
			global::Intersoft.Crosslight.Android.Resource.Layout.toast = global::CustomPresenter.Android.Resource.Layout.toast;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastlayout = global::CustomPresenter.Android.Resource.Layout.toastlayout;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastshadow = global::CustomPresenter.Android.Resource.Layout.toastshadow;
			global::Intersoft.Crosslight.Android.Resource.Layout.toastshape = global::CustomPresenter.Android.Resource.Layout.toastshape;
			global::Intersoft.Crosslight.Android.Resource.Layout.viewpagerindicatortab = global::CustomPresenter.Android.Resource.Layout.viewpagerindicatortab;
			global::Intersoft.Crosslight.Android.Resource.Layout.viewpagerwithtab = global::CustomPresenter.Android.Resource.Layout.viewpagerwithtab;
			global::Intersoft.Crosslight.Android.Resource.Layout.viewpagerwithtabstrip = global::CustomPresenter.Android.Resource.Layout.viewpagerwithtabstrip;
			global::Intersoft.Crosslight.Android.Resource.String.Add = global::CustomPresenter.Android.Resource.String.Add;
			global::Intersoft.Crosslight.Android.Resource.String.Cancel = global::CustomPresenter.Android.Resource.String.Cancel;
			global::Intersoft.Crosslight.Android.Resource.String.CheckAll = global::CustomPresenter.Android.Resource.String.CheckAll;
			global::Intersoft.Crosslight.Android.Resource.String.ChooseFromGallery = global::CustomPresenter.Android.Resource.String.ChooseFromGallery;
			global::Intersoft.Crosslight.Android.Resource.String.CloseDrawer = global::CustomPresenter.Android.Resource.String.CloseDrawer;
			global::Intersoft.Crosslight.Android.Resource.String.Delete = global::CustomPresenter.Android.Resource.String.Delete;
			global::Intersoft.Crosslight.Android.Resource.String.DeleteImage = global::CustomPresenter.Android.Resource.String.DeleteImage;
			global::Intersoft.Crosslight.Android.Resource.String.More = global::CustomPresenter.Android.Resource.String.More;
			global::Intersoft.Crosslight.Android.Resource.String.OpenDrawer = global::CustomPresenter.Android.Resource.String.OpenDrawer;
			global::Intersoft.Crosslight.Android.Resource.String.Save = global::CustomPresenter.Android.Resource.String.Save;
			global::Intersoft.Crosslight.Android.Resource.String.SelectImage = global::CustomPresenter.Android.Resource.String.SelectImage;
			global::Intersoft.Crosslight.Android.Resource.String.TakePhoto = global::CustomPresenter.Android.Resource.String.TakePhoto;
			global::Intersoft.Crosslight.Android.Resource.String.UncheckAll = global::CustomPresenter.Android.Resource.String.UncheckAll;
			global::Intersoft.Crosslight.Android.Resource.String.pull_to_refresh_pull_label = global::CustomPresenter.Android.Resource.String.pull_to_refresh_pull_label;
			global::Intersoft.Crosslight.Android.Resource.String.pull_to_refresh_refreshing_label = global::CustomPresenter.Android.Resource.String.pull_to_refresh_refreshing_label;
			global::Intersoft.Crosslight.Android.Resource.String.pull_to_refresh_release_label = global::CustomPresenter.Android.Resource.String.pull_to_refresh_release_label;
			global::Intersoft.Crosslight.Android.Resource.String.spb_default_speed = global::CustomPresenter.Android.Resource.String.spb_default_speed;
			global::Intersoft.Crosslight.Android.Resource.Style.ListItem = global::CustomPresenter.Android.Resource.Style.ListItem;
			global::Intersoft.Crosslight.Android.Resource.Style.SmoothProgressBar = global::CustomPresenter.Android.Resource.Style.SmoothProgressBar;
			global::Intersoft.Crosslight.Android.Resource.Style.TextAppearance_Custom_PtrHeader_Title = global::CustomPresenter.Android.Resource.Style.TextAppearance_Custom_PtrHeader_Title;
			global::Intersoft.Crosslight.Android.Resource.Style.TextAppearance_Small = global::CustomPresenter.Android.Resource.Style.TextAppearance_Small;
			global::Intersoft.Crosslight.Android.Resource.Style.TextViewStyle = global::CustomPresenter.Android.Resource.Style.TextViewStyle;
			global::Intersoft.Crosslight.Android.Resource.Style.Theme_Holo_CustomPtrHeader = global::CustomPresenter.Android.Resource.Style.Theme_Holo_CustomPtrHeader;
			global::Intersoft.Crosslight.Android.Resource.Style.Theme_SmoothProgressBarDefaults = global::CustomPresenter.Android.Resource.Style.Theme_SmoothProgressBarDefaults;
			global::Intersoft.Crosslight.Android.Resource.Style.Widget_Custom_PtrHeader = global::CustomPresenter.Android.Resource.Style.Widget_Custom_PtrHeader;
			global::Intersoft.Crosslight.Android.Resource.Style.Widget_ProgressBar_PullToRefresh = global::CustomPresenter.Android.Resource.Style.Widget_ProgressBar_PullToRefresh;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderBackground = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderBackground;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderHeight = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderHeight;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderTitleTextAppearance = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrHeaderTitleTextAppearance;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarColor = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarColor;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarHeight = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarHeight;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarStyle = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrProgressBarStyle;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrPullText = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrPullText;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrRefreshingText = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrRefreshingText;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshHeader_ptrReleaseText = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshHeader_ptrReleaseText;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshView = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshView;
			global::Intersoft.Crosslight.Android.Resource.Styleable.PullToRefreshView_ptrViewDelegateClass = global::CustomPresenter.Android.Resource.Styleable.PullToRefreshView_ptrViewDelegateClass;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spbStyle = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spbStyle;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_color = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_color;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_colors = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_colors;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_interpolator = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_interpolator;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_mirror_mode = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_mirror_mode;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_reversed = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_reversed;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_sections_count = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_sections_count;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_speed = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_speed;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_stroke_separator_length = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_stroke_separator_length;
			global::Intersoft.Crosslight.Android.Resource.Styleable.SmoothProgressBar_spb_stroke_width = global::CustomPresenter.Android.Resource.Styleable.SmoothProgressBar_spb_stroke_width;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int toast_enter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toast_exit = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int transition_bottomtop = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int transition_fadein = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int transition_fadeout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int transition_leftright = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int transition_rightleft = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int transition_topbottom = 2130968585;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int select_image_dialog = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderBackground = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderHeight = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderStyle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int ptrHeaderTitleTextAppearance = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ptrProgressBarColor = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int ptrProgressBarHeight = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int ptrProgressBarStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int ptrPullText = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ptrRefreshingText = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int ptrReleaseText = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int ptrViewDelegateClass = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int spbStyle = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int spb_color = 2130771980;
			
			// aapt resource value: 0x7f010014
			public const int spb_colors = 2130771988;
			
			// aapt resource value: 0x7f010011
			public const int spb_interpolator = 2130771985;
			
			// aapt resource value: 0x7f010013
			public const int spb_mirror_mode = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int spb_reversed = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int spb_sections_count = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int spb_speed = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int spb_stroke_separator_length = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int spb_stroke_width = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0001
			public const int spb_default_mirror_mode = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int spb_default_reversed = 2131492864;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int bright_foreground_dark = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_progress_bar_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int holo_dark_green = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int listviewbackgroundselector = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int spb_default_color = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int vpi__background_holo_dark = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int vpi__background_holo_light = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int vpi__bright_foreground_disabled_holo_dark = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int vpi__bright_foreground_disabled_holo_light = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int vpi__bright_foreground_holo_dark = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int vpi__bright_foreground_holo_light = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int vpi__bright_foreground_inverse_holo_dark = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int vpi__bright_foreground_inverse_holo_light = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int vpi__dark_theme = 2131230733;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090002
			public const int ptr_progress_bar_stroke_width = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int spb_default_stroke_separator_length = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int spb_default_stroke_width = 2131296257;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_check_off_focused_holo_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check_on_pressed_holo_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int leftdrawershadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_splash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rightdrawershadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int toast_frame_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int vpi__tab_indicator = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int vpi__tab_selected_focused_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vpi__tab_selected_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vpi__tab_selected_pressed_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vpi__tab_unselected_focused_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int vpi__tab_unselected_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vpi__tab_unselected_pressed_holo = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070020
			public const int Button1 = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int ControlsPlaceholder = 2131165225;
			
			// aapt resource value: 0x7f07000b
			public const int DatePickerWidget = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int DateTimePickerDateWidget = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int DateTimePickerTimeWidget = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int EditorContainer = 2131165198;
			
			// aapt resource value: 0x7f070021
			public const int FooterLabel = 2131165217;
			
			// aapt resource value: 0x7f070014
			public const int FooterLayout = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int FooterText = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int FormContainer = 2131165203;
			
			// aapt resource value: 0x7f07001f
			public const int GreetingLabel = 2131165215;
			
			// aapt resource value: 0x7f070010
			public const int HeaderLayout = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int HeaderSeparator = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int HeaderText = 2131165201;
			
			// aapt resource value: 0x7f070028
			public const int ImagePlaceholder = 2131165224;
			
			// aapt resource value: 0x7f07002f
			public const int ImageView = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int InnerLayout = 2131165233;
			
			// aapt resource value: 0x7f07002a
			public const int InternalSeekBar = 2131165226;
			
			// aapt resource value: 0x7f070036
			public const int PagerTabStrip = 2131165238;
			
			// aapt resource value: 0x7f07002b
			public const int SpinnerWidget = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int Switch = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int TabContainer = 2131165229;
			
			// aapt resource value: 0x7f070032
			public const int TabIcon = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int TabPageIndicator = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int TabTitle = 2131165235;
			
			// aapt resource value: 0x7f07000a
			public const int Text1 = 2131165194;
			
			// aapt resource value: 0x7f07002e
			public const int Text2 = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int TimePickerWidget = 2131165232;
			
			// aapt resource value: 0x7f07000f
			public const int TitleText = 2131165199;
			
			// aapt resource value: 0x7f070035
			public const int ViewPager = 2131165237;
			
			// aapt resource value: 0x7f070023
			public const int detailFrame = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int drawer_layout = 2131165220;
			
			// aapt resource value: 0x7f070016
			public const int fragmentActivityLayout = 2131165206;
			
			// aapt resource value: 0x7f07001d
			public const int fragmentBody = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int fragmentFooter = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int fragmentHeader = 2131165212;
			
			// aapt resource value: 0x7f070000
			public const int inside = 2131165184;
			
			// aapt resource value: 0x7f070026
			public const int left_navdrawer = 2131165222;
			
			// aapt resource value: 0x7f070018
			public const int listContainer = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int listViewFooter = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int listViewHeader = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int listViewProgressbar = 2131165211;
			
			// aapt resource value: 0x7f070025
			public const int maincontent_navdrawer = 2131165221;
			
			// aapt resource value: 0x7f070022
			public const int masterFrame = 2131165218;
			
			// aapt resource value: 0x7f070001
			public const int outside = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int progressContainer = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int progress_bar = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int ptr_content = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int ptr_progress = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int ptr_text = 2131165191;
			
			// aapt resource value: 0x7f070027
			public const int right_navdrawer = 2131165223;
			
			// aapt resource value: 0x7f070002
			public const int spb_interpolator_accelerate = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int spb_interpolator_acceleratedecelerate = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int spb_interpolator_decelerate = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int spb_interpolator_linear = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0001
			public const int spb_default_interpolator = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int spb_default_sections_count = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f050000
			public const int accelerate_quad = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int decelerate_quad = 2131034113;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activitylargeindicator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activitysmallindicator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activitytranslucentindicator = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int buttonwidget = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int checkboxwidget = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int datepickerwidget = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int datetimepickerwidget = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int default_header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int formlayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int formlayoutdetailonly = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int formlayoutleftdetail = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int formlayoutrightdetail = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int formlayoutrowdetail = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int formsectionlayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragmentactivitylayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int imagepickerwidget = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int imageviewwidget = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int listgroupsectionheaderlayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int listgroupsectionlayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int listviewfooterlayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int listviewheaderlayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int listviewprogressbarlayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int maincontainer = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MainLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int masterdetailfragmentlayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int navigationdrawerlayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int radiobuttonwidget = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int sectionimageswithfieldslayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int sectionlayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int seekbarwidget = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int selectionwidget = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int spinnerdropdownitemlayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int spinnerlayout = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int spinnerwidget = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int switchwidget = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int tabcontainer = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int tabfragmentlayout = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int tablecellleftdetail = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int tablecellrightdetail = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int tablecellsubtitle = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int tablecellsubtitlewithimage = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int textfieldview = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int timepickerwidget = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int toast = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int toastlayout = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int toastshadow = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int toastshape = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int viewpagerindicatortab = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int viewpagerwithtab = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int viewpagerwithtabstrip = 2130903089;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0001
			public const int Add = 2131427329;
			
			// aapt resource value: 0x7f0b0011
			public const int ApplicationName = 2131427345;
			
			// aapt resource value: 0x7f0b0002
			public const int Cancel = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int CheckAll = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int ChooseFromGallery = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int CloseDrawer = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int Delete = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int DeleteImage = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int More = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int OpenDrawer = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int Save = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int SelectImage = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int TakePhoto = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int UncheckAll = 2131427341;
			
			// aapt resource value: 0x7f0b0012
			public const int Update = 2131427346;
			
			// aapt resource value: 0x7f0b000e
			public const int pull_to_refresh_pull_label = 2131427342;
			
			// aapt resource value: 0x7f0b0010
			public const int pull_to_refresh_refreshing_label = 2131427344;
			
			// aapt resource value: 0x7f0b000f
			public const int pull_to_refresh_release_label = 2131427343;
			
			// aapt resource value: 0x7f0b0000
			public const int spb_default_speed = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0d0000
			public const int ListItem = 2131558400;
			
			// aapt resource value: 0x7f0d0002
			public const int SmoothProgressBar = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int TextAppearance_Custom_PtrHeader_Title = 2131558403;
			
			// aapt resource value: 0x7f0d0001
			public const int TextAppearance_Small = 2131558401;
			
			// aapt resource value: 0x7f0d0004
			public const int TextViewStyle = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int Theme_Holo_CustomPtrHeader = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public const int Theme_SmoothProgressBarDefaults = 2131558406;
			
			// aapt resource value: 0x7f0d0009
			public const int Theme_Splash = 2131558409;
			
			// aapt resource value: 0x7f0d0008
			public const int Widget_Custom_PtrHeader = 2131558408;
			
			// aapt resource value: 0x7f0d0007
			public const int Widget_ProgressBar_PullToRefresh = 2131558407;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefreshHeader = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int PullToRefreshHeader_ptrHeaderBackground = 0;
			
			// aapt resource value: 1
			public const int PullToRefreshHeader_ptrHeaderHeight = 1;
			
			// aapt resource value: 2
			public const int PullToRefreshHeader_ptrHeaderTitleTextAppearance = 2;
			
			// aapt resource value: 3
			public const int PullToRefreshHeader_ptrProgressBarColor = 3;
			
			// aapt resource value: 5
			public const int PullToRefreshHeader_ptrProgressBarHeight = 5;
			
			// aapt resource value: 4
			public const int PullToRefreshHeader_ptrProgressBarStyle = 4;
			
			// aapt resource value: 6
			public const int PullToRefreshHeader_ptrPullText = 6;
			
			// aapt resource value: 7
			public const int PullToRefreshHeader_ptrRefreshingText = 7;
			
			// aapt resource value: 8
			public const int PullToRefreshHeader_ptrReleaseText = 8;
			
			public static int[] PullToRefreshView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int PullToRefreshView_ptrViewDelegateClass = 0;
			
			public static int[] SmoothProgressBar = new int[]
			{
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int SmoothProgressBar_spbStyle = 0;
			
			// aapt resource value: 1
			public const int SmoothProgressBar_spb_color = 1;
			
			// aapt resource value: 9
			public const int SmoothProgressBar_spb_colors = 9;
			
			// aapt resource value: 6
			public const int SmoothProgressBar_spb_interpolator = 6;
			
			// aapt resource value: 8
			public const int SmoothProgressBar_spb_mirror_mode = 8;
			
			// aapt resource value: 7
			public const int SmoothProgressBar_spb_reversed = 7;
			
			// aapt resource value: 4
			public const int SmoothProgressBar_spb_sections_count = 4;
			
			// aapt resource value: 5
			public const int SmoothProgressBar_spb_speed = 5;
			
			// aapt resource value: 3
			public const int SmoothProgressBar_spb_stroke_separator_length = 3;
			
			// aapt resource value: 2
			public const int SmoothProgressBar_spb_stroke_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
